apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hellowvers
  name: hellowvers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellowvers
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hellowvers
    spec:
      containers:
      - image: rogerpease/hellow_versioned_image:0.1.0
        name: hellow-versioned
        resources: {}
status: {}
