apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hellowvers
  name: hellowvers
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hellowvers
  type: NodePort
status:
  loadBalancer: {}
