apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hellowfilesys
  name: hellowfilesys
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000 
  selector:
    app: hellowfilesys
  type: NodePort
status:
  loadBalancer: {}
